sudo: required
dist: trusty
language: node_js
addons:
  apt:
    packages:
    - icnsutils
    - graphicsmagick
node_js:
- '6'
install:
- npm install
script:
- npm run fonts
- npm run transpile
- npm run dist
- cp dist/*.deb dist/sonos-controller-unofficial-amd64.deb
deploy:
  overwrite: true
  provider: releases
  api_key:
    secure: Pr4/K3blDB1eS21B9tp9XIYXvhlHaDP5Z6PkK8qwSmPFzBZ+swiMuTqLZDjCF5aBDL5SS7Jh7xK4iNuuPH0BOvRy4m0IxR7l9TRA2XN2Fw5PgEUBg5SqnCqivECCd4MHdL9ZLBtE4Khcf9uD5BEEZbPDp0bwas2sZsWl0wmACsk=
  file: dist/sonos-controller-unofficial-amd64.deb
  on:
    tags: true
    repo: pascalopitz/unoffical-sonos-controller-for-linux
