sudo: required
dist: trusty
language: node_js
addons:
  apt:
    packages:
    - icnsutils
    - graphicsmagick
node_js:
- '13'
script:
- npm run lint
- npm run test
- npm run fonts
- npm run transpile
- npm run dist
- ls -lah dist
deploy:
  skip_cleanup: true
  overwrite: true
  provider: releases
  file_glob: true
  file: dist/sonos-controller-unofficial*
  api_key:
    secure: fe4iMbeIWqTxwgw1QmjuuYgCkgLf7vPx3D28y7xqrW6tHk6vgIybNXpj3m4jH3QxndEsUx48jMpL9UR29anDb9JGYvsYrDadidn1d+tUXP9fqFxFpA6A2BWIfANMCUECfm8hS18WZHP1WsmR7ZfbQsV75XtUsYLUNaW8XN+6Ca4=
  on:
    tags: true
    repo: pascalopitz/unoffical-sonos-controller-for-linux
cache:
  directories:
  - "$HOME/.cache/electron-builder"
  - "$HOME/.cache/electron"
env:
  global:
    secure: VnWlTfDl002iIsySDU4gPN7qjfedU4HV81MenqWKdlkwPlUV0nTBX/NBpVhvMPc6F7t2uV52LVEwadUoZN/ZzaYqGcui3y4B3cAfNKOmcUOe9YI1kpHDVtjzLZJ6x9qGHtz19xpQuy7wGEKY07YMivZD39riROXV3VHH9GBZe5w=
