branches:
  only:
  - master
sudo: required
dist: trusty
language: node_js
addons:
  artifacts:
    paths:
      - $(ls $HOME/dist/*deb)
  apt:
    packages:
    - icnsutils
    - graphicsmagick
node_js:
- '6'
install:
- npm install
script:
- npm run dist
